version: "3.8"
name: excel
services:
  excelwebapi:
    container_name: ExcelWebApi
    image: excelwebapi:dev
    build:
      context: ./
      dockerfile: ExcelWebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - ./ExcelWebAPI/Database:/app/Database

